#安装 mariadb 和 httpd php php-fpm php-mysql,建议使用老师写的版本
---
- name: install db
  hosts: dbservers
  tasks:
    - name: install db
      yum:
        name: mariadb-server
        state: latest
- name: install httpd
  hosts: webservers
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: install php
      yum:
        name: php
        state: latest
    - name: install php-fpm
      yum:
        name: php-fpm
        state: latest
    - name: install php-server
      yum:
        name: php-mysql
        state: latest



